### ISSUE TITLE
Error in second build step

### ISSUE THREAD

**Issue by petschni** [joshisa/piwikstart#1]
Hello,

when deploying it to Bluemix the second build step fails with:

`⚒  Pre-creating RedisCloud Service named [piwikredis]
_customer_script.sh: line 51: [: !=: unary operator expected`

and finally then:

`FAILED
Could not find service sendmail to bind to piwikstudioshamburg
`

**Comment by joshisa** [comment]
Thanks for the report.  With regard to the second one, I think sendgrid dropped their free plan.  Pipeline Shell Script probably needs a refresh to reflect current catalog. Will take a look.

**Comment by joshisa** [comment]
@petschni I did a major refresh of the files.  Made the redis service creation more resilient to errors.  Revved api, plugin and platform versions up. This repo now cleanly deploys piwik-3-0-0-beta3.  I've also included the new toolchain button process which has a really nice experience integrated with github.  The beta3 UI has some graphics placeholders (squares) - but seems to be otherwise very functional.  If you're still interested in 2.x, I can look into making a separate branch in a few weeks.  Feel free to reopen this issue if you run into problems.
